//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Szpital
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wizyty
    {
        public int IdWizyty { get; set; }
        public Nullable<int> IdPracownika { get; set; }
        public Nullable<int> IdKlienta { get; set; }
        public Nullable<System.DateTime> DataWizyty { get; set; }
        public Nullable<decimal> Kwota { get; set; }
    
        public virtual Klienci Klienci { get; set; }
        public virtual Pracownicy Pracownicy { get; set; }
    }
}
